### ISSUE TITLE
Initialization Not Working Properly

### ISSUE THREAD

**Issue by jlgutenson** [c-h-david/rapid#15]
We're running RAPID in a forecast mode.  We've noticed that initialization isn't occurring correctly for us in the latest version of the code.  We've reverted back to a previous version and initialization works.  I'm nNot sure if any changes were made to the Qinit processing.  Did any recent updates change the initialization process?

**Comment by c-h-david** [comment]
@jlgutenson, it's been quite a while since i last modified the initialization process.  Probably a year or two.  In these modifications, the file type for initialization was modified from CSV to netCDF in order to allow for double precision floating points and hence for an exact restart capability.  Before I look at the version control log, it would be helpful if you could provide a couple of tag/release numbers: one for a version that "works", and another one for a version that "doesn't work". The initialization is regularly tested as part of the contiguous integration procedure and has been performing as expected as far as I know.  Another potential thing to look at is the recent (within the last 2-3 months) transition from netCDF3 to netCDF4. Thanks for the feedback!
