### ISSUE TITLE
[enhancement] Design choice in reading `rapid_namelist` by default vs specifying file as runtime option?

### ISSUE THREAD

**Issue by KMarkert** [c-h-david/rapid#21]
Hi Cedric,

I am working more with RAPID, I find it to be a very nice model and appreciate it! I am curious though as to why the design choice for the CLI is to read the `rapid_namelist` file directly within the model versus having the user supply the config file as an input (i.e. `./rapid -i my_run_namelist`). 

I understand the current guidance is for users to provide symbolic links to the namelist config, especially with multiple simulations. However, I find it more intuitive if users were to provide the config file explicitly to the model, this way there is no ambiguity for inputs into the model when automating. 

Was there a specific reason for this? Is there leeway (or interest) to update the model CLI so that users provide the input?

**Comment by c-h-david** [comment]
Hi Kel, this is a very good point and an excellent suggestion. The hard-coded `rapid_namelist` file name was more of an ease of implementation choice rather than a design choice. I totally agree that allowing for a runtime option to provide one's own namelist file is a legitimate path forward. My only hesitation in doing so is that such a new feature would require editing all unit tests (the many `./tst/tst_pub_repr*` files) and I suspect this could be quite time consuming. Happy to work together on this if you're interested, and able to help out.  And thanks for your kind words!

**Comment by KMarkert** [comment]
I did a little digging on this, and is seems that if there is interest to support allowing a user argument for the namelist files, a simple interface can easily be added.

[rapid_main.F90#L49](https://github.com/c-h-david/rapid/blob/master/src/rapid_main.F90#L49) can be changed to the following code:

```diff
-namelist_file='./rapid_namelist'
+character(len=32) :: arg
+call get_command_argument(1, arg)
+select case (arg)
+case('-nl','--namelist')
+    call get_command_argument(2,namelist_file)
+case default
+   print *, 'Unrecognized command-line option: ', arg
+    stop
+end select
```

Users can specify the namelist file explicitly (`./rapid -nl my_run_namelist`). More options can be added to provide help or print version number but this is atleast a start to a CLI for rapid.

**Comment by KMarkert** [comment]
Sorry, I didn't see your comment before my previous one! Glad to hear you are open to expanding the CLI. 

I am happy to take a stab at updating rapid_main.F90 with some arg parsing on a new branch and can try working through the unit testing. I will probably need some help with the unit tests though...

**Comment by c-h-david** [comment]
Hi Kel, thanks so much for looking into this and making suggested changes!  Impressively quick, frankly.  There is quite a bit to digest for me in there, it might be best to try to set up a meeting together so that you can guide me through your proposed modifications.  At first glance, it seems to me we could perhaps retain the default `rapid_namelist` when ommiting the `-nl` flag.  This would allow not having to update the unit tests. Also, while I'm a big fan of removing unnecessary spaces in the code (keeping it clean!), these changes make it feel like a lot happened besides the intended feature enhancement. Overall, the most minimal the proposed changes are, the easier it is for me to follow what happened!  I'll try follow up on email for a meeting.

**Comment by KMarkert** [comment]
Hi Cedric, Yes, I would be happy to talk with you on these changes. I agree that we can change the default behavior to read the default `rapid_namelist` as before to keep things simple.

On the point of many changes, I completely understand your point. It looks like my text editor removed a lot of trailing whitespace from the code automatically (like this [example](https://github.com/c-h-david/rapid/pull/22/files#diff-bc80c8ec09d04e5b45a0c916a16106d1201d7e4442e65f6b14482487ae00e00bL32)). My intent was not to make that many changes and what I actually changed is far less than what is shown, sorry about that!

I can try reverting back to the old commit prior to changes and prevent the white space removal. Then for the feature, change back the default behavior if that will be best for this PR. Please let me know.

**Comment by elyssac02** [comment]
Just adding another comment here....thank you @KMarkert for bringing this up! I believe I have found a beneficial use case of having the user supply the namelist file as an input. I've been working on adding RAPID to my university's HPC cluster by converting the Docker image to a Singularity image. Since the contents of the Singularity container cannot be modified without having root permissions and since the namelist is read directly within the model as `rapid_namelist`, I believe this means that a unique container has to be created for each simulation you want to run (each container with unique arguments in `rapid_namelist`). Please correct me if I'm wrong, as I just started learning how to use Singularity. I'm wondering if the proposed changes here will circumvent the need to create multiple containers.

**Comment by elyssac02** [comment]
> Since the contents of the Singularity container cannot be modified without having root permissions and since the namelist is read directly within the model as `rapid_namelist`, I believe this means that a unique container has to be created for each simulation you want to run (each container with unique arguments in `rapid_namelist`).

Just adding an update to this. Instead of creating a unique image for each simulation, I was able to rebuild RAPID with the correct file path for the `namelist_file` variable in the `rapid_main.F90` script and then go through the process of converting the Docker image to a Singularity image on HPC. However, I believe the proposed changes here would still be beneficial for running multiple simulations (deploying multiple containers) simultaneously on HPC.

**Comment by NO645** [comment]
@KMarkert @elyssac02 

I have found that to prevent having a separate singularity or docker container for each simulation you can launch a container with a mounted directory that contains the namelist, then from inside the mounted directory if you call the rapid executable with:

`/home/rapid/src/rapid`

it will run a simulation using that namelist. This also works outside of containers, you just have to use the absolute path to your rapid executable. What I do is name my folders with a nomenclature that reflects the namelist's contents and then call the executable inside each of them in succession. I can run multiple simulations from a single installation/container without the need to touch anything in the rapid folders or create symbolic links.

**Comment by c-h-david** [comment]
Thanks everyone for your patience and suggestions. Specifying the namelist at runtime is now possible starting with the most recent tag for RAPID: [20230427](https://github.com/c-h-david/rapid/releases/tag/20230427). Here is how to use it:
`./rapid --namelist mynamelist` or `./rapid -nl mynamelist`
The old name `rapid_namelist` is still used as default value.
Special thanks to @KMarkert for great code suggestions!
